export const MOVIE_API_URL = 'https://api.themoviedb.org/3/discover/movie';
export const SERIE_API_URL = 'https://api.themoviedb.org/3/discover/tv';
export const PERSON_API_URL = 'https://api.themoviedb.org/3/person/popular';
export const API_KEY = '3c27cf2da95a9372232a01814c2dc0ee';
export const IMG_URL = 'https://image.tmdb.org/t/p/original';
export const GenreMap: Record<number, string> = {
    28: "Acción",
    12: "Aventura",
    16: "Animación",
    35: "Comedia",
    80: "Crimen",
    99: "Documental",
    18: "Drama",
    10751: "Familiar",
    14: "Fantasía",
    36: "Historia",
    27: "Terror",
    10402: "Música",
    9648: "Misterio",
    10749: "Romance",
    878: "Ciencia Ficción",
    10770: "Película de TV",
    53: "Suspenso",
    10752: "Guerra",
    37: "Western",
    10759: "Acción y Aventura",
    10762: "Infantil",
    10763: "Noticias",
    10764: "Reality Show",
    10765: "Ciencia Ficción y Fantasía",
    10766: "Telenovela",
    10767: "Talk Show",
    10768: "Guerra y Política"
};

export const LanguageMap: Record<string, string> = {
    xx: "Sin idioma",
    aa: "Afar",
    af: "Afrikáans",
    ak: "Akan",
    an: "Aragonés",
    as: "Asamés",
    av: "Avar",
    ae: "Avéstico",
    ay: "Aimara",
    az: "Azerbaiyano",
    ba: "Baskir",
    bm: "Bambara",
    bn: "Bengalí",
    bi: "Bislama",
    bo: "Tibetano",
    bs: "Bosnio",
    br: "Bretón",
    ca: "Catalán",
    cs: "Checo",
    ch: "Chamorro",
    ce: "Checheno",
    cu: "Eslavo eclesiástico",
    cv: "Chuvasio",
    kw: "Córnico",
    co: "Corso",
    cr: "Cree",
    cy: "Galés",
    da: "Danés",
    de: "Alemán",
    dv: "Maldivo",
    dz: "Dzongkha",
    en: "Inglés",
    eo: "Esperanto",
    et: "Estonio",
    eu: "Euskera",
    fo: "Feroés",
    fj: "Fiyiano",
    fi: "Finés",
    fr: "Francés",
    fy: "Frisón",
    ff: "Fulah",
    gd: "Gaélico",
    ga: "Irlandés",
    gl: "Gallego",
    gv: "Manés",
    gn: "Guaraní",
    gu: "Guyaratí",
    ht: "Criollo haitiano",
    ha: "Hausa",
    sh: "Serbocroata",
    hz: "Herero",
    ho: "Hiri Motu",
    hr: "Croata",
    hu: "Húngaro",
    ig: "Igbo",
    io: "Ido",
    ii: "Yi",
    iu: "Inuktitut",
    ie: "Interlingue",
    ia: "Interlingua",
    id: "Indonesio",
    ik: "Inupiaq",
    is: "Islandés",
    it: "Italiano",
    jv: "Javanés",
    ja: "Japonés",
    kl: "Groenlandés",
    kn: "Canarés",
    ks: "Cachemir",
    ka: "Georgiano",
    kr: "Kanuri",
    kk: "Kazajo",
    km: "Jemer",
    ki: "Kikuyu",
    rw: "Kinyarwanda",
    ky: "Kirguís",
    kv: "Komi",
    kg: "Kongo",
    ko: "Coreano",
    kj: "Kuanyama",
    ku: "Kurdo",
    lo: "Lao",
    la: "Latín",
    lv: "Letón",
    li: "Limburgués",
    ln: "Lingala",
    lt: "Lituano",
    lb: "Luxemburgués",
    lu: "Luba-Katanga",
    lg: "Ganda",
    mh: "Marshalés",
    ml: "Malayalam",
    mr: "Maratí",
    mg: "Malgache",
    mt: "Maltés",
    mo: "Moldavo",
    mn: "Mongol",
    mi: "Maorí",
    ms: "Malayo",
    my: "Birmano",
    na: "Nauruano",
    nv: "Navajo",
    nr: "Ndebele del Sur",
    nd: "Ndebele del Norte",
    ng: "Ndonga",
    ne: "Nepalí",
    nl: "Neerlandés",
    nn: "Noruego Nynorsk",
    nb: "Noruego Bokmål",
    no: "Noruego",
    ny: "Chichewa",
    oc: "Occitano",
    oj: "Ojibwa",
    or: "Oriya",
    om: "Oromo",
    os: "Osetio",
    pa: "Panyabí",
    pi: "Pali",
    pl: "Polaco",
    pt: "Portugués",
    qu: "Quechua",
    rm: "Romanche",
    ro: "Rumano",
    rn: "Kirundi",
    ru: "Ruso",
    sg: "Sango",
    sa: "Sánscrito",
    si: "Cingalés",
    sk: "Eslovaco",
    sl: "Esloveno",
    se: "Sami del Norte",
    sm: "Samoano",
    sn: "Shona",
    sd: "Sindhi",
    so: "Somalí",
    st: "Sesotho",
    es: "Español",
    su: "Sundanés",
    sw: "Suajili",
    ss: "Swati",
    sv: "Sueco",
    ta: "Tamil",
    te: "Telugu",
    tg: "Tayiko",
    th: "Tailandés",
    ti: "Tigriña",
    tk: "Turcomano",
    tl: "Tagalo",
    tn: "Setsuana",
    to: "Tongano",
    tr: "Turco",
    ts: "Tsonga",
    tt: "Tártaro",
    tw: "Twi",
    ty: "Tahitiano",
    ug: "Uigur",
    uk: "Ucraniano",
    ur: "Urdú",
    uz: "Uzbeko",
    ve: "Venda",
    vi: "Vietnamita",
    vo: "Volapük",
    wa: "Valón",
    wo: "Wolof",
    xh: "Xhosa",
    yi: "Yidis",
    yo: "Yoruba",
    za: "Zhuang",
    zh: "Chino",
    zu: "Zulú",
  };
  
  
  
  